const Joi = require('joi');

exports.participant = Joi.object().keys({
  forename: Joi.string().min(1).max(30).required(),
  surename: Joi.string().min(1).max(30).required(),
  mobile: Joi.string().regex(/^\d+$/).required(),
  landline: Joi.string().regex(/^\d+$/),
  borough: Joi.string().required(),
  kin_contact: Joi.string().regex(/^\d+$/),
  ni_number: Joi.string().regex(/^([a-zA-Z]){2}([0-9]){6}([a-zA-Z])$/),
  date_of_birth: Joi.date().required(),
  email: Joi.string().email({ minDomainAtoms: 2 }),
  address: Joi.optional(),
  gender: Joi.valid(['male', 'female']).required(),
  martial_status: Joi.valid(['single', 'married', 'widowed', 'separated', 'divorced', 'cff']).required(),
  sexual_orientatuin: Joi.valid([
    'lesbian',
    'gay',
    'bisexual',
    'queer',
    'straight',
    'something else',
    'decline to answer',
  ]).required(),
  dependents: Joi.valid(['no dependent', 'from 1 to 5', 'from 5 to 10', 'more than 10']).required(),
  ethincity: Joi.valid([
    'Asian or Asian British – Bangladeshi',
    'Mixed – White and Asian',
    'Asian or Asian British – Indian',
    'Mixed - White and Black African',
    'Asian or Asian British – Pakistani',
    'Mixed – White and Black Caribbean',
    'Asian or Asian British – Any other',
    'Mixed - any other mixed background',
    'Black or Black British – African',
    'White – British',
    'Black or Black British – Caribbean',
    'White – Irish',
    'Black or Black British – Any Other',
    'White – Any Other Background',
    'Chinese',
    'Any Other',
    'Not Known or Provided',
  ]).required(),
  numeracy_level: Joi.number().optional(),
  nationality: Joi.string().optional(),
  postcode: Joi.string().optional(),
  support_required: Joi.string().optional(),
  cscs_number: Joi.valid(['yes', 'no']).required(),
  cscs_support: Joi.string().optional(),
  leteracy_level: Joi.valid([
    'Entry Level 1',
    'Entry Level 2',
    'Entry Level 3',
    'Level 1',
    'Level 2',
    'GCSE',
    'A-Level',
  ]).required(),
  case_worker: Joi.string().optional(),
  disability_and_medical: Joi.string().optional(),
  employment_outcomes: Joi.string().optional(),
  inPrison: Joi.bool().required(),
  reoffending: Joi.optional(),
  error: Joi.optional(),
});
